name: Check ticket

on:
  workflow_dispatch:
  push:

jobs:
  check-ticket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check repository files
        run: |
          echo "Branch:"
          git branch --show-current
          echo "Commit:"
          git rev-parse HEAD
          echo "Files:"
          ls -la
          echo "Alert file:"
          ls -la alert.py

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run alert
        run: python Alert.py
